baseURL = "https://albilaga.id"
languageCode = "id"
DefaultContentLanguage = "id"
title = "Albilaga Blog"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

[params]
title = "Hai, saya Albilaga"
author = "Albilaga"
description = "Software engineer dari Malang"
profilePicture = "images/avatar.png"
keywords = ""
favicon = "images/favicon.icon"
customCss = []
customJs = []
mainSections = ["posts"]
# images = ["images/site-feature-image.png"]
# Google Site Verification
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

## Math settings
[params.math]
enable = false # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/albilaga/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/albilaga"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/albilaga"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:albilaga.@pm.me"

## Menu items

[menu]

#[[menu.main]]
#name = "Beranda"
#identifier = "home"
#weight = 100
#url = "/"

#[[menu.main]]
#name = "Blog"
#weight = 200
#identifier = "posts"
#url = "/post/"

#  [[menu.main]]
#  name = "Tentang"
#  weight = 300
#  identifier = "about"
#  url = "/about/"

[languages]
[languages.id]
weight = 1
languageName = "Indonesia"
[languages.en]
weight = 2
title = "Hi, I am Albilaga"
description = "A software engineer based in Malang"
languageName = "English"
#[[languages.en.menu.main]]
#url    = "/en/"
#name   = "Home"
#weight = 100
[[languages.en.menu.main]]
#name = "Blog"
#weight = 200
#identifier = "posts"
#url = "/post/"
