baseURL = "https://albilaga.id"
languageCode = "id"
DefaultContentLanguage = "id"
title = "Albilaga Blog"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

[params]
favicon = "images/favicon.icon"
mainSections = ["posts"]
author = "Albilaga"
profilePicture = "images/avatar.png"

## Math settings
[params.math]
enable = false
use = "katex"

## Social links
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/albilaga/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/albilaga"

[[params.socialIcons]]
icon = "fab fa-bluesky"
title = "bluesky"
url = "https://bsky.app/profile/albilaga.id"

[[params.socialIcons]]
icon = "fab fa-x-twitter"
title = "Twitter"
url = "https://x.com/albilaga"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:albilaga.@pm.me"

[languages]
[languages.id]
weight = 1
params.title = "Hai, saya Albilaga"
params.description = "Software engineer dari Malang"
languageName = "Indonesia"

[languages.en]
weight = 2
params.title = "Hi, I am Albilaga"
params.description = "A software engineer based in Malang"
languageName = "English"

[imaging]
[imaging.exif]
disableDate = true
disableLatLong = true
excludeFields = ''
includeFields = ''

[module]
# uncomment line below for temporary local development of module
# replacements = "github.com/lxndrblz/anatole -> ../../anatole"
[[module.imports]]
path = "github.com/lxndrblz/anatole"
disable = false
